# Generated by Django 6.0.6 on 2026-06-25 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pieza', models.CharField(max_length=100)),
                ('stock_disponible', models.PositiveIntegerField(default=0)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'repuestos',
            },
        ),
        migrations.CreateModel(
            name='OrdenServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_falla', models.TextField()),
                ('estado', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('DIAGNOSTICO', 'Diagnostico'), ('REPARACION', 'Reparacion'), ('LISTO', 'Listo')], default='RECIBIDO', max_length=20)),
                ('costo_mano_obra', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_pagar', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ordenes', to='reparaciones.cliente')),
            ],
            options={
                'db_table': 'ordenes_servicio',
            },
        ),
        migrations.CreateModel(
            name='DetalleInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_usada', models.PositiveIntegerField()),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='reparaciones.ordenservicio')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='usos', to='reparaciones.repuesto')),
            ],
            options={
                'db_table': 'detalle_inventario',
            },
        ),
    ]
