# Generated by Django 6.0.6 on 2026-06-27 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repuesto',
            name='stock_disponible',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='repuesto',
            table=None,
        ),
    ]
