# Generated by Django 6.0.6 on 2026-06-27 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparaciones', '0002_alter_repuesto_stock_disponible_alter_repuesto_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenservicio',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
