# Generated by Django 6.0.6 on 2026-06-28 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparaciones', '0003_ordenservicio_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenservicio',
            name='numero_orden',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
