# Generated by Django 6.0.6 on 2026-06-28 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparaciones', '0004_ordenservicio_numero_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenservicio',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANFERENCIA', 'Transferencia')], max_length=20, null=True),
        ),
    ]
