# Generated by Django 6.0.6 on 2026-06-28 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparaciones', '0005_ordenservicio_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenservicio',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
